-- MuzicMania: Supabase Database Schema (v1.0)
-- Este script inicializa las tablas necesarias para el backend profesional.

-- 1. TABLA DE PERFILES (Extensión de Auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,

  CONSTRAINT username_length CHECK (char_length(username) >= 3)
);

-- Habilitar RLS para perfiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Los usuarios pueden ver cualquier perfil." ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Los usuarios pueden editar su propio perfil." ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

-- 2. TABLA DE LEADERBOARDS (Récords de canciones)
CREATE TABLE IF NOT EXISTS public.leaderboards (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  song_id TEXT NOT NULL,
  score INTEGER NOT NULL DEFAULT 0,
  accuracy DECIMAL NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS para leaderboards
ALTER TABLE public.leaderboards ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Cualquiera puede ver la tabla de clasificación." ON public.leaderboards
  FOR SELECT USING (true);

CREATE POLICY "Solo usuarios autenticados pueden subir puntuaciones." ON public.leaderboards
  FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- 3. FUNCIONES Y TRIGGERS (Auto-creación de perfil al registrarse)
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, username, avatar_url)
  VALUES (new.id, new.raw_user_meta_data->>'username', new.raw_user_meta_data->>'avatar_url');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
